/* global scrollY, getComputedStyle, document, innerWidth */
import {chromium, expect} from '@playwright/test'
const base=process.env.ARCHIVE_TEST_URL || 'http://127.0.0.1:5199'
const browser=await chromium.launch({channel:'chrome',headless:true})
try {
 for (const width of [1440,390]) {
  const context=await browser.newContext({viewport:{width,height:900}, reducedMotion:'reduce'})
  const page=await context.newPage()
  await page.goto(`${base}/archives/writings/`)
  const folder=page.locator('.archive-library')
  await expect(folder.getByRole('heading',{name:'Writings',exact:true})).toBeVisible()
  await expect.poll(()=>folder.locator('.archive-library-entry').count()).toBe(33)
  await expect.poll(()=>folder.evaluate(el=>Math.abs(el.getBoundingClientRect().top-32))).toBeLessThan(3)
  await expect(folder.getByRole('heading',{name:'Writings',exact:true})).toBeFocused()
  const search=folder.getByRole('searchbox')
  await search.fill('zzzxynothing')
  await expect(folder.getByRole('heading',{name:'Nothing here matches yet.'})).toBeVisible()
  await folder.getByRole('button',{name:'Show all work'}).click()
  await expect(search).toBeFocused()
  await folder.getByRole('combobox').selectOption('oldest')
  const dates=await folder.locator('time').evaluateAll(els=>els.map(el=>Date.parse(el.dateTime)))
  expect(dates).toEqual([...dates].sort((a,b)=>a-b))
  await folder.getByRole('combobox').selectOption('title')
  const titles=await folder.locator('h4').allTextContents()
  expect(titles).toEqual([...titles].sort((a,b)=>a.localeCompare(b)))
  await search.fill('master of my prompt')
  const article=folder.locator('.archive-library-entry').first()
  await article.click()
  await expect(page.locator('.native-post h1')).toBeVisible()
  await expect.poll(()=>page.evaluate(()=>scrollY)).toBeLessThan(3)
  await page.goBack()
  await expect(page.locator('.archive-library input')).toHaveValue('master of my prompt')
  await expect(page.locator('.archive-library select')).toHaveValue('title')
  await page.getByRole('button',{name:'Clear filters'}).click()
  await page.locator('.archive-library select').selectOption('newest')
  await page.locator('.archive-library-entry').last().scrollIntoViewIfNeeded()
  expect(await page.locator('.archive-library').evaluate(el=>{for(let p=el;p;p=p.parentElement)if(Number(getComputedStyle(p).opacity)<1)return false;return true})).toBe(true)
  await page.getByRole('button',{name:'All folders'}).click()
  await expect(page.locator('button#writings')).toBeFocused()
  await page.getByRole('button',{name:/Folder.*Vlogumentaries/s}).click()
  const filters=page.getByRole('group',{name:'Filter by collection'})
  await expect(filters).toBeVisible()
  await filters.getByRole('button').nth(1).click()
  await expect(filters.getByRole('button').nth(1)).toHaveAttribute('aria-pressed','true')
  expect(await page.locator('.archive-library-entry').count()).toBeGreaterThan(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:`/private/tmp/archive-vlogs-${width}.png`})
  await page.getByRole('button',{name:'All folders'}).click()
  await page.getByRole('button',{name:/Folder.*Writings/s}).click()
  await expect(page.locator('.archive-library h3')).toHaveText('Writings')
  await expect.poll(()=>page.locator('.archive-library').evaluate(el=>Math.abs(el.getBoundingClientRect().top-32))).toBeLessThan(8)
  await page.screenshot({path:`/private/tmp/archive-final-${width}.png`})
  console.log(`${width}px: deep link, search, sorting, article/back, focus, collections, readability, and width passed`)
  await context.close()
 }
} finally {await browser.close()}
