// This file is generated by scripts/build-content.mjs. Do not edit by hand.
import type { ArchiveItem, Experience, SiteConfig } from "./types"

export const site = {
  "name": "Muhammad Hadi Yusufali",
  "shortName": "M Hadi",
  "role": "Creator at the intersection of tech and creativity",
  "description": "Writing my story as you read it. A creator experimenting across many mediums at the intersection of tech and creativity.",
  "email": "hello@mhadifilms.com",
  "bio": "I’m a creator experimenting across many mediums at the intersection of tech and creativity. With over 8 years of experience in digital media, I’m currently Chief of Staff at sync. labs, where we’re building technology to modify humans in video.\n\nI've had the privilege of learning from the world's top creatives including UCLA professors and Emmy-winning filmmakers, allowing my contribution to hundreds of projects gaining 1M+ views and international recognition.",
  "polaroids": [
    {
      "src": "/media/polaroid-on-set.webp",
      "alt": "Muhammad Hadi Yusufali operating a cinema camera outdoors",
      "caption": "on set"
    },
    {
      "src": "/media/polaroid-beach.webp",
      "alt": "Muhammad Hadi Yusufali filming at sunset on a beach",
      "caption": "golden hour"
    },
    {
      "src": "/media/polaroid-mountains.webp",
      "alt": "Muhammad Hadi Yusufali photographing a mountain landscape",
      "caption": "the lens"
    },
    {
      "src": "/media/polaroid-podcast.webp",
      "alt": "Muhammad Hadi Yusufali recording Journey Tellers in a podcast studio",
      "caption": "journey tellers"
    },
    {
      "src": "/media/polaroid-camera.webp",
      "alt": "Muhammad Hadi Yusufali filming with a handheld camera and shotgun microphone",
      "caption": "behind camera"
    }
  ],
  "socials": [
    {
      "label": "Substack",
      "href": "https://mhadimedia.substack.com"
    },
    {
      "label": "YouTube",
      "href": "https://www.youtube.com/@mhadifilms"
    },
    {
      "label": "Instagram",
      "href": "https://www.instagram.com/mhadifilms",
      "embedScriptSrc": "https://elfsightcdn.com/platform.js",
      "embedAppId": "4bca295b-052a-430d-a96c-9f1fd7c63633",
      "embedTitle": "Latest Instagram posts"
    },
    {
      "label": "Twitter",
      "href": "https://x.com/mhadifilms"
    },
    {
      "label": "Linkedin",
      "href": "https://www.linkedin.com/in/mhadifilms"
    }
  ]
} satisfies SiteConfig

export const experiences = [
  {
    "title": "Chief of Staff at sync. labs",
    "slug": "sync-labs",
    "company": "sync. labs",
    "role": "Chief of Staff",
    "location": "San Francisco, CA",
    "dateStart": "2023-08-01",
    "summary": "Grew with sync. from early growth work into production leadership and now Chief of Staff, helping turn high-end AI video research into work that survives real clients, real footage, and real deadlines.",
    "tags": [
      "operations",
      "production",
      "product",
      "ai video"
    ],
    "href": "https://sync.so",
    "logo": "/media/figma-mhadi-camera.png",
    "html": "<p>At sync. labs, my job has moved with the company: Growth Intern, Growth Marketer, Head of Production, and now Chief of Staff. The thread through all of it has been helping the product, the team, and the work that leaves the building become sharper.</p>\n<p>Role progression:</p>\n<ul>\n<li>Chief of Staff, full-time, Feb 2026 to present.</li>\n<li>Head of Production, full-time, Jun 2024 to Mar 2026.</li>\n<li>Growth Marketer, part-time, Nov 2023 to Jun 2024.</li>\n<li>Growth Intern, contract, Aug 2023 to Nov 2023.</li>\n</ul>\n<p>What I worked on:</p>\n<ul>\n<li>Built systems around messy, high-stakes creative work instead of treating video like a clean demo.</li>\n<li>Worked closely with product feedback, production needs, and the company narrative.</li>\n<li>Brought an editor&#39;s eye to AI video, content, and production workflows where a few frames can be the difference between impressive and believable.</li>\n</ul>\n"
  },
  {
    "title": "Multimedia Intern at TMS Media",
    "slug": "tms-media",
    "company": "TMS Media",
    "role": "Multimedia Intern",
    "dateStart": "2023-06-01",
    "dateEnd": "2023-09-01",
    "summary": "Worked on podcast editing, short-form content, and content ideation for TMS Media.",
    "tags": [
      "video editing",
      "video production",
      "podcast editing",
      "content"
    ],
    "logo": "/media/polaroid-podcast.webp",
    "html": "<p>TMS Media gave me a more focused production environment for quick-turn media work. The work sat close to the edit: making conversations tighter, shaping clips for social, and thinking through what a piece of content needed before it hit the timeline.</p>\n<p>What this included:</p>\n<ul>\n<li>Podcast editing and cleanup.</li>\n<li>Short-form content for social distribution.</li>\n<li>Content ideation for repeatable media formats.</li>\n</ul>\n"
  },
  {
    "title": "Chief Marketing Officer at coglayer",
    "slug": "coglayer",
    "company": "coglayer",
    "role": "Chief Marketing Officer",
    "dateStart": "2023-03-01",
    "dateEnd": "2024-01-01",
    "summary": "Helped build and scale coglayer from an early product into a learning tool with 35,000 users.",
    "tags": [
      "marketing",
      "product",
      "project management",
      "seo"
    ],
    "logo": "/media/polaroid-camera.webp",
    "html": "<p>coglayer was a product and growth chapter: part positioning, part product management, part figuring out what students and users actually needed from a tool that called itself training wheels for your brain.</p>\n<p>Highlights:</p>\n<ul>\n<li>Helped build and scale from 0 to 35,000 users.</li>\n<li>Worked across product management, project management, beta testing, marketing, and SEO.</li>\n<li>Helped translate a product idea into clearer messaging, feedback loops, and launch motion.</li>\n</ul>\n"
  },
  {
    "title": "Founder & Host at Journey Tellers",
    "slug": "journey-tellers",
    "company": "Journey Tellers",
    "role": "Founder, Host & Producer",
    "location": "San Francisco Bay Area",
    "dateStart": "2023-01-01",
    "dateEnd": "2025-01-01",
    "summary": "Built and hosted a long-form podcast with Ali Almathkur about real people, hard-earned lessons, and the story of the Muslim West.",
    "tags": [
      "podcast",
      "storytelling",
      "production",
      "audio"
    ],
    "href": "https://awaiten.com/podcast/",
    "logo": "/media/polaroid-podcast.webp",
    "html": "<p>Journey Tellers started as a way to have slower, better conversations than social media usually allows. I co-hosted with Ali Almathkur and worked across guest research, interview prep, production, editing, and distribution.</p>\n<p>Highlights:</p>\n<ul>\n<li>Hosted founders, community builders, creatives, and people with stories that deserved more time.</li>\n<li>Produced episodes for YouTube and major podcast platforms.</li>\n<li>Used the show as a way to practice listening, pacing, and long-form narrative.</li>\n</ul>\n"
  },
  {
    "title": "UCLA Summer Sessions",
    "slug": "ucla-summer-sessions",
    "company": "UCLA Summer Sessions",
    "role": "Film & Storytelling Study",
    "location": "Los Angeles, CA",
    "dateStart": "2022",
    "dateEnd": "2022",
    "summary": "Studied film, story structure, and production craft through UCLA Summer Sessions, learning from instructors who brought a working filmmaker's eye to the classroom.",
    "tags": [
      "film study",
      "storytelling",
      "directing",
      "craft"
    ],
    "logo": "/media/polaroid-beach.webp",
    "html": "<p>UCLA helped sharpen the way I think about story before a camera ever turns on. The strongest lessons were practical: how scenes carry pressure, how performances change a cut, and how structure can make a small piece feel bigger than its budget.</p>\n<p>What stayed with me:</p>\n<ul>\n<li>A more disciplined way to break down scripts, scenes, and character motivation.</li>\n<li>Classroom critique from instructors with real production experience.</li>\n<li>A stronger foundation for the directing, editing, and documentary work I took on afterward.</li>\n</ul>\n"
  },
  {
    "title": "Co-Founder at SR Studios",
    "slug": "sr-studios",
    "company": "SR Studios",
    "role": "Co-Founder",
    "dateStart": "2020-09-01",
    "dateEnd": "2021-07-01",
    "summary": "Co-founded a student-led multimedia organization that helped young creatives collaborate across borders.",
    "tags": [
      "content creation",
      "video editing",
      "teaching",
      "marketing"
    ],
    "logo": "/media/polaroid-mountains.webp",
    "html": "<p>SR Studios was an early lesson in creative leadership: getting students from different places to make things together, learn practical media skills, and ship collaborative projects before everyone had a polished portfolio.</p>\n<p>Highlights:</p>\n<ul>\n<li>Co-founded the student-led organization.</li>\n<li>Helped students learn photography, editing, and multimedia basics.</li>\n<li>Led marketing while helping shape the group into a real creative home for young collaborators.</li>\n</ul>\n"
  },
  {
    "title": "Co-Founder at Awaiten Films",
    "slug": "awaiten-films",
    "company": "Awaiten Films",
    "role": "Co-Founder",
    "location": "Bay Area, CA",
    "dateStart": "2018-09-01",
    "summary": "Co-founded a Bay Area-based production company dedicated to sharing real stories and experiences with the world.",
    "tags": [
      "production",
      "directing",
      "editing",
      "cinematography"
    ],
    "href": "https://awaiten.com",
    "logo": "/media/polaroid-on-set.webp",
    "html": "<p>Awaiten is where I learned how to make the work hold up outside of my own head. We combine technical craft with narrative depth to create visual content for real communities, real clients, and real stories.</p>\n<p>Highlights:</p>\n<ul>\n<li>Co-founded the studio with Aalyan Aamir.</li>\n<li>Worked across directing, cinematography, editing, motion graphics, production, and delivery.</li>\n<li>Built more than seven years of production experience through the studio.</li>\n<li>Helped produce community, brand, documentary, and event work reaching 1M+ views.</li>\n</ul>\n"
  },
  {
    "title": "Selected past collaborators",
    "slug": "early-projects",
    "company": "Wondertime · ALI · SABA · Loquat · others",
    "role": "Editor, VFX, Producer",
    "dateStart": "2017",
    "dateEnd": "2023",
    "summary": "Early work across community media, websites, short documentaries, nonprofit projects, and scrappy production teams.",
    "tags": [
      "editing",
      "vfx",
      "producing",
      "community"
    ],
    "logo": "/media/polaroid-mountains.webp",
    "html": "<p>Before the current chapter, I built range by saying yes to a lot of different creative problems. Some needed an editor. Some needed a producer. Some needed a website, a visual system, or someone willing to figure it out.</p>\n<p>Selected areas:</p>\n<ul>\n<li>Editing and visual effects for community and documentary projects.</li>\n<li>Web and creative systems work for organizations and early-stage ideas.</li>\n<li>Production support for Wondertime, ALI, SABA, Loquat, and other collaborators.</li>\n</ul>\n"
  },
  {
    "title": "Filmmaker & Editor (Freelance)",
    "slug": "independent-filmmaker",
    "company": "Freelance",
    "role": "Filmmaker, Editor, VFX",
    "location": "Worldwide",
    "dateStart": "2017",
    "summary": "Eight-plus years editing, shooting, fixing, and finishing videos for clients, communities, events, and personal projects.",
    "tags": [
      "editing",
      "vfx",
      "directing",
      "cinematography"
    ],
    "logo": "/media/polaroid-camera.webp",
    "html": "<p>Freelance work taught me the whole production loop. Find the story, plan what can actually be shot, capture enough to make the edit work, clean the details, and deliver something people want to watch.</p>\n<p>What this includes:</p>\n<ul>\n<li>Editing, color, sound cleanup, titles, and motion graphics.</li>\n<li>Camera operation and directing for documentary, event, brand, and community work.</li>\n<li>Practical fixes for small teams, tight budgets, bad rooms, and ambitious ideas.</li>\n</ul>\n"
  }
] satisfies Experience[]

export const archives = [
  {
    "slug": "instagram-1",
    "platform": "Instagram",
    "title": "@mhadifilms on Instagram",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "image": "/media/polaroid-on-set.webp",
    "summary": "Profile connection for behind-the-scenes filmmaking, production stills, travel frames, and visual experiments. Instagram does not provide a reliable public feed here, so this card links directly to the profile."
  },
  {
    "slug": "linkedin-2",
    "platform": "Linkedin",
    "title": "I built a DaVinci Resolve MCP",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://www.linkedin.com/posts/mhadifilms_i-built-a-davinci-resolve-mcp-so-claude-can-activity-7455733839189946368-QHAG",
    "image": "/media/polaroid-camera.webp",
    "summary": "A public LinkedIn post about building a Python library, CLI, and local MCP server so Claude can help edit video timelines faster."
  },
  {
    "slug": "twitter-1",
    "platform": "Twitter",
    "title": "@mhadifilms on X",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://x.com/mhadifilms",
    "image": "/media/polaroid-camera.webp",
    "summary": "Profile connection for short-form notes on creative tools, AI video, filmmaking, and current builds. Public X feeds require API access, so this card links directly to the profile."
  },
  {
    "slug": "substack-building-an-app-every-day-but-idk-how-to-code-1",
    "platform": "Substack",
    "title": "building an app every day but idk how to code...",
    "date": "2025-12-26",
    "href": "https://mhadimedia.substack.com/p/building-an-app-every-day-but-idk",
    "image": "https://substackcdn.com/image/fetch/$s_!SadC!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F9a983c58-9242-4321-b4ec-91ff4ef3be3c_1584x446.png",
    "summary": "for the past month, I’ve been building an app almost every single day using AI to bring whatever random idea I have to life. mac apps, websites, python..."
  },
  {
    "slug": "youtube-we-spent-a-week-exploring-tanzania-1",
    "platform": "YouTube",
    "title": "We Spent a Week Exploring Tanzania",
    "date": "2025-09-27",
    "href": "https://www.youtube.com/watch?v=Vy6LJhDH3Bk",
    "image": "https://i.ytimg.com/vi/Vy6LJhDH3Bk/sddefault.jpg",
    "summary": "A few months ago, I had the chance to travel to Tanzania with friends for a week. Join us we chill with lions, swim with dolphins, visit one of the biggest..."
  },
  {
    "slug": "substack-we-made-a-movie-in-six-weeks-2",
    "platform": "Substack",
    "title": "we made a movie in six weeks.",
    "date": "2025-09-26",
    "href": "https://mhadimedia.substack.com/p/we-made-a-movie-in-six-weeks",
    "image": "https://substackcdn.com/image/fetch/$s_!03A4!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3efef56e-c3ca-4e88-8d6a-f60b5ee38384_6240x4160.jpeg",
    "summary": "a few weeks ago, I had the chance to edit my first official short film featuring an entire production crew, and professional actors. it was literally a dream..."
  },
  {
    "slug": "substack-to-know-what-you-want-learn-what-you-don-t-3",
    "platform": "Substack",
    "title": "to know what you want, learn what you don't",
    "date": "2025-09-03",
    "href": "https://mhadimedia.substack.com/p/to-know-what-you-want-learn-what",
    "image": "https://substackcdn.com/image/fetch/$s_!8FHv!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7678f84c-6612-49d9-83bf-2aacf2f0df23.heic",
    "summary": "Suddenly, amidst all the chaos, confusion, and commotion, There was clarity . …is what I wish I could be saying right now 😬 Welcome back to Creative Chaos, a..."
  },
  {
    "slug": "substack-just-rented-seven-electric-scooters-in-one-day-4",
    "platform": "Substack",
    "title": "just rented seven electric scooters in one day",
    "date": "2025-08-22",
    "href": "https://mhadimedia.substack.com/p/just-rented-seven-electric-scooters",
    "image": "https://substackcdn.com/image/fetch/$s_!CAAe!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7c30175d-e7c0-41ed-a222-6091a0205ff3.heic",
    "summary": "clarity . that’s all I wanted when I decided to spend six weeks of my summer living away from family in Los Angeles. some clarity on whether I should… a...."
  },
  {
    "slug": "youtube-two-weeks-in-the-middle-east-with-my-school-part-3-2",
    "platform": "YouTube",
    "title": "Two Weeks in the Middle East with My School (Part 3)",
    "date": "2024-12-21",
    "href": "https://www.youtube.com/watch?v=6EblOyuUj34",
    "image": "https://i.ytimg.com/vi/6EblOyuUj34/maxresdefault.jpg",
    "summary": "Watch part two first: https://youtu.be/TCrVwEoOvMk During the winter break of 2023, I went on a life-changing trip to the Middle East along with my high school..."
  },
  {
    "slug": "youtube-two-weeks-in-the-middle-east-with-my-school-part-2-3",
    "platform": "YouTube",
    "title": "Two Weeks in the Middle East with My School (Part 2)",
    "date": "2024-11-28",
    "href": "https://www.youtube.com/watch?v=TCrVwEoOvMk",
    "image": "https://i.ytimg.com/vi/TCrVwEoOvMk/maxresdefault.jpg",
    "summary": "Watch the part one: https://youtu.be/iPT8JzCvBTE During the winter break of 2023, I went on a life-changing trip to the Middle East along with my high school..."
  },
  {
    "slug": "youtube-we-turned-a-youth-camp-into-a-documentary-4",
    "platform": "YouTube",
    "title": "We Turned a Youth Camp into a Documentary",
    "date": "2024-10-31",
    "href": "https://www.youtube.com/watch?v=04p3ls98W7Y",
    "image": "https://i.ytimg.com/vi/04p3ls98W7Y/maxresdefault.jpg",
    "summary": "Watch the full documentary on @JourneyTellers: https://www.youtube.com/watch?v=zkvAHvcw8DE In May 2024, the Journey Tellers team partnered with Camp Noor to..."
  },
  {
    "slug": "linkedin-1",
    "platform": "Linkedin",
    "title": "Why is AI Scary? Robots Already Control You.",
    "date": "2024-02-01T00:00:00.000Z",
    "href": "https://www.linkedin.com/pulse/why-ai-scary-robots-already-control-you-muhammad-hadi-yusufali",
    "image": "/media/figma-mhadi-camera.png",
    "summary": "A public LinkedIn article about how recommendation algorithms already shape attention, behavior, and creative culture."
  }
] satisfies ArchiveItem[]
