// This file is generated by scripts/build-content.mjs. Do not edit by hand.
import type { ArchiveItem, Experience, SiteConfig } from "./types"

export const site = {
  "name": "Muhammad Hadi Yusufali",
  "shortName": "M Hadi",
  "role": "Creator at the intersection of tech and creativity",
  "description": "Writing my story as you read it. A creator experimenting across many mediums at the intersection of tech and creativity.",
  "email": "hello@mhadi.tv",
  "bio": "I'm a filmmaker and content creator with over seven years of experience. I'm currently Chief of Staff & Head of Story at sync. — a research lab modifying humans in video.\n\nOn the side, I co-founded Awaiten Films, a Bay Area production company with my friend Aalyan, and I co-host Journey Tellers, a podcast on the story of the Muslim West. I've had the privilege of working with some of the best creatives I know on a few hundred projects so far.",
  "polaroids": [
    {
      "src": "/media/polaroid-1.jpg",
      "alt": "On set",
      "caption": "on set"
    },
    {
      "src": "/media/polaroid-2.jpg",
      "alt": "Behind the camera",
      "caption": "the lens"
    },
    {
      "src": "/media/polaroid-3.jpg",
      "alt": "Sync labs",
      "caption": "sync. labs"
    },
    {
      "src": "/media/polaroid-4.jpg",
      "alt": "UCLA",
      "caption": "ucla"
    }
  ],
  "socials": [
    {
      "label": "Linkedin",
      "href": "https://www.linkedin.com/in/mhadi"
    },
    {
      "label": "Twitter",
      "href": "https://twitter.com/mhadifilms"
    },
    {
      "label": "Instagram",
      "href": "https://www.instagram.com/mhadifilms"
    },
    {
      "label": "Substack",
      "href": "https://mhadi.substack.com"
    },
    {
      "label": "YouTube",
      "href": "https://www.youtube.com/@mhadifilms"
    }
  ]
} satisfies SiteConfig

export const experiences = [
  {
    "title": "Chief of Staff & Head of Story at sync.",
    "slug": "sync-labs",
    "company": "sync.",
    "role": "Chief of Staff & Head of Story",
    "location": "San Francisco, CA",
    "dateStart": "2024",
    "summary": "Building the team and the narrative behind sync. — the research lab modifying humans in video.",
    "tags": [
      "operations",
      "storytelling",
      "brand",
      "product"
    ],
    "href": "https://sync.so",
    "html": ""
  },
  {
    "title": "Co-Host at Journey Tellers",
    "slug": "journey-tellers",
    "company": "Journey Tellers",
    "role": "Co-Host & Producer",
    "location": "Worldwide",
    "dateStart": "2023",
    "summary": "A podcast on reading, writing, and celebrating the story of the Muslim West, with co-host Ali Almathkur.",
    "tags": [
      "podcast",
      "storytelling",
      "audio"
    ],
    "href": "https://jtpodcast.com",
    "html": ""
  },
  {
    "title": "Co-Founder at Awaiten Films",
    "slug": "awaiten-films",
    "company": "Awaiten Films",
    "role": "Co-Founder",
    "location": "Bay Area, CA",
    "dateStart": "2022",
    "summary": "A Bay Area production company built with Aalyan Aamir, focused on quality multimedia work at prices that make sense.",
    "tags": [
      "production",
      "directing",
      "editing"
    ],
    "href": "https://awaiten.co",
    "html": ""
  },
  {
    "title": "Selected past collaborators",
    "slug": "early-projects",
    "company": "Wondertime · ALI · SABA · Loquat · others",
    "role": "Editor, VFX, Producer",
    "dateStart": "2017",
    "dateEnd": "2023",
    "summary": "Years of multimedia work across community, brand, and documentary — from the Wondertime show to the ALI website to short documentaries with Loquat.",
    "tags": [
      "editing",
      "vfx",
      "producing",
      "community"
    ],
    "html": ""
  },
  {
    "title": "Filmmaker & Editor (Freelance)",
    "slug": "independent-filmmaker",
    "company": "Freelance",
    "role": "Filmmaker, Editor, VFX",
    "location": "Worldwide",
    "dateStart": "2017",
    "summary": "Seven-plus years contributing to hundreds of projects — video editing, visual effects, and directing for clients across the country and abroad.",
    "tags": [
      "editing",
      "vfx",
      "directing",
      "cinematography"
    ],
    "html": ""
  }
] satisfies Experience[]

export const archives = [
  {
    "slug": "substack-1",
    "platform": "Substack",
    "title": "Writing my story as you read it",
    "date": "2026-05-09T00:00:00.000Z",
    "href": "https://mhadi.substack.com",
    "summary": "An intro essay on this site and what comes next."
  },
  {
    "slug": "twitter-1",
    "platform": "Twitter",
    "title": "Notes on building creative tools",
    "date": "2026-05-02T00:00:00.000Z",
    "href": "https://twitter.com/mhadifilms",
    "summary": "A short thread on building tools for creators that don't suck."
  },
  {
    "slug": "substack-3",
    "platform": "Substack",
    "title": "Letters from a chief of staff",
    "date": "2026-04-30T00:00:00.000Z",
    "href": "https://mhadi.substack.com",
    "summary": "A monthly note on what I'm learning in the room with founders and engineers."
  },
  {
    "slug": "twitter-4",
    "platform": "Twitter",
    "title": "Shot of the day",
    "date": "2026-04-22T00:00:00.000Z",
    "href": "https://twitter.com/mhadifilms",
    "summary": "A frame from an unreleased short. Still figuring out how it ends."
  },
  {
    "slug": "twitter-2",
    "platform": "Twitter",
    "title": "Sync. labs shipped a new model",
    "date": "2026-04-18T00:00:00.000Z",
    "href": "https://twitter.com/mhadifilms",
    "summary": "Quick reaction to the latest release."
  },
  {
    "slug": "instagram-1",
    "platform": "Instagram",
    "title": "On set, late golden hour",
    "date": "2026-04-12T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "summary": "Behind the camera on a shoot in the hills."
  },
  {
    "slug": "instagram-2",
    "platform": "Instagram",
    "title": "A frame from the new piece",
    "date": "2026-03-29T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "summary": "Still from the latest short."
  },
  {
    "slug": "youtube-2",
    "platform": "YouTube",
    "title": "Inside sync. labs — a year of building",
    "date": "2026-03-18T00:00:00.000Z",
    "href": "https://www.youtube.com/@mhadifilms",
    "summary": "An informal walkthrough of what we shipped, what broke, and what's next."
  },
  {
    "slug": "instagram-3",
    "platform": "Instagram",
    "title": "Camera test, 35mm",
    "date": "2026-03-10T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "summary": "Quick test with a new lens."
  },
  {
    "slug": "substack-2",
    "platform": "Substack",
    "title": "The director as a prompt engineer",
    "date": "2026-03-02T00:00:00.000Z",
    "href": "https://mhadi.substack.com",
    "summary": "How direction translates almost one-to-one to the prompts we write at sync."
  },
  {
    "slug": "instagram-4",
    "platform": "Instagram",
    "title": "Studio, around midnight",
    "date": "2026-02-22T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "summary": "Long edit nights."
  },
  {
    "slug": "linkedin-4",
    "platform": "Linkedin",
    "title": "Talks I gave this season",
    "date": "2026-02-18T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadi",
    "summary": "Three campuses, two studios, one panel — slides + recordings inside."
  },
  {
    "slug": "twitter-3",
    "platform": "Twitter",
    "title": "A thread on lip-sync as a UX problem",
    "date": "2026-01-09T00:00:00.000Z",
    "href": "https://twitter.com/mhadifilms",
    "summary": "Why getting the mouth right matters more than the rest of the face."
  },
  {
    "slug": "youtube-1",
    "platform": "YouTube",
    "title": "A short film, one year later",
    "date": "2026-01-08T00:00:00.000Z",
    "href": "https://www.youtube.com/@mhadifilms",
    "summary": "A look back at the making of last year's short."
  },
  {
    "slug": "substack-4",
    "platform": "Substack",
    "title": "Things I wish I knew at twenty",
    "date": "2025-12-12T00:00:00.000Z",
    "href": "https://mhadi.substack.com",
    "summary": "A short list, written for someone who isn't me anymore."
  },
  {
    "slug": "linkedin-2",
    "platform": "Linkedin",
    "title": "How creative teams ship faster with AI tooling",
    "date": "2025-11-20T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadi",
    "summary": "Notes from a year of pairing filmmakers with model‑native workflows."
  },
  {
    "slug": "youtube-3",
    "platform": "YouTube",
    "title": "How I cut a 3-minute short in a day",
    "date": "2025-10-04T00:00:00.000Z",
    "href": "https://www.youtube.com/@mhadifilms",
    "summary": "A start-to-finish edit, no music license drama — promise."
  },
  {
    "slug": "linkedin-3",
    "platform": "Linkedin",
    "title": "Hiring at sync. labs — Founding Researcher",
    "date": "2025-08-04T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadi",
    "summary": "We're a small team building generative video models — come help us push them out the door."
  },
  {
    "slug": "youtube-4",
    "platform": "YouTube",
    "title": "A small interview with a big filmmaker",
    "date": "2025-07-22T00:00:00.000Z",
    "href": "https://www.youtube.com/@mhadifilms",
    "summary": "An hour of conversation with someone whose work raised me."
  },
  {
    "slug": "linkedin-1",
    "platform": "Linkedin",
    "title": "Joined sync. labs as Chief of Staff",
    "date": "2024-06-15T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadi",
    "summary": "Thrilled to be helping build the technology that modifies humans in video."
  }
] satisfies ArchiveItem[]
