// This file is generated by scripts/build-content.mjs. Do not edit by hand.
import type { ArchiveItem, Experience, SiteConfig } from "./types"

export const site = {
  "name": "Muhammad Hadi Yusufali",
  "shortName": "M Hadi",
  "role": "Creator at the intersection of tech and creativity",
  "description": "Writing my story as you read it. A creator experimenting across many mediums at the intersection of tech and creativity.",
  "email": "hello@mhadifilms.com",
  "bio": "I’m a creator experimenting across many mediums at the intersection of tech and creativity. With over 8 years of experience in digital media, I’m currently Chief of Staff at sync. labs, where we’re building technology to modify humans in video.\n\nI've had the privilege of learning from the world's top creatives including UCLA professors and Emmy-winning filmmakers, allowing my contribution to hundreds of projects gaining 1M+ views and international recognition.",
  "polaroids": [
    {
      "src": "/media/polaroid-on-set.webp",
      "alt": "Muhammad Hadi Yusufali operating a cinema camera outdoors",
      "caption": "on set"
    },
    {
      "src": "/media/polaroid-beach.webp",
      "alt": "Muhammad Hadi Yusufali filming at sunset on a beach",
      "caption": "golden hour"
    },
    {
      "src": "/media/polaroid-mountains.webp",
      "alt": "Muhammad Hadi Yusufali photographing a mountain landscape",
      "caption": "the lens"
    },
    {
      "src": "/media/polaroid-podcast.webp",
      "alt": "Muhammad Hadi Yusufali recording Journey Tellers in a podcast studio",
      "caption": "journey tellers"
    },
    {
      "src": "/media/polaroid-camera.webp",
      "alt": "Muhammad Hadi Yusufali filming with a handheld camera and shotgun microphone",
      "caption": "behind camera"
    }
  ],
  "socials": [
    {
      "label": "Linkedin",
      "href": "https://www.linkedin.com/in/mhadimedia"
    },
    {
      "label": "Twitter",
      "href": "https://x.com/mhadifilms"
    },
    {
      "label": "Instagram",
      "href": "https://www.instagram.com/mhadifilms"
    },
    {
      "label": "Substack",
      "href": "https://mhadi.substack.com"
    },
    {
      "label": "YouTube",
      "href": "https://www.youtube.com/@mhadifilms"
    }
  ]
} satisfies SiteConfig

export const experiences = [
  {
    "title": "Chief of Staff & Head of Production at sync. labs",
    "slug": "sync-labs",
    "company": "sync. labs",
    "role": "Chief of Staff & Head of Production",
    "location": "San Francisco, CA",
    "dateStart": "2024",
    "summary": "Helping sync. labs turn high-end AI video research into production work that can survive real clients, real footage, and real deadlines.",
    "tags": [
      "operations",
      "production",
      "product",
      "ai video"
    ],
    "href": "https://sync.so",
    "logo": "/media/figma-mhadi-camera.png",
    "html": "<p>At sync. labs, my job sits between the product, the team, and the work that leaves the building. I help shape production workflows, customer delivery, internal operations, and the story we tell around the technology.</p>\n<p>Highlights:</p>\n<ul>\n<li>Built systems around messy, high-stakes creative work instead of treating video like a clean demo.</li>\n<li>Worked closely with product feedback, production needs, and the company narrative.</li>\n<li>Brought an editor&#39;s eye to AI video, where a few frames can be the difference between impressive and believable.</li>\n</ul>\n"
  },
  {
    "title": "Founder & Host at Journey Tellers",
    "slug": "journey-tellers",
    "company": "Journey Tellers",
    "role": "Founder, Host & Producer",
    "location": "Worldwide",
    "dateStart": "2023",
    "dateEnd": "2025",
    "summary": "Built and hosted a long-form podcast with Ali Almathkur about real people, hard-earned lessons, and the story of the Muslim West.",
    "tags": [
      "podcast",
      "storytelling",
      "production",
      "audio"
    ],
    "href": "https://jtpodcast.com",
    "logo": "/media/polaroid-podcast.webp",
    "html": "<p>Journey Tellers started as a way to have slower, better conversations than social media usually allows. I co-hosted with Ali Almathkur and worked across guest research, interview prep, production, editing, and distribution.</p>\n<p>Highlights:</p>\n<ul>\n<li>Hosted founders, community builders, creatives, and people with stories that deserved more time.</li>\n<li>Produced episodes for YouTube and major podcast platforms.</li>\n<li>Used the show as a way to practice listening, pacing, and long-form narrative.</li>\n</ul>\n"
  },
  {
    "title": "UCLA Summer Sessions",
    "slug": "ucla-summer-sessions",
    "company": "UCLA Summer Sessions",
    "role": "Film & Storytelling Study",
    "location": "Los Angeles, CA",
    "dateStart": "2022",
    "dateEnd": "2022",
    "summary": "Studied film, story structure, and production craft through UCLA Summer Sessions, learning from instructors who brought a working filmmaker's eye to the classroom.",
    "tags": [
      "film study",
      "storytelling",
      "directing",
      "craft"
    ],
    "logo": "/media/polaroid-beach.webp",
    "html": "<p>UCLA helped sharpen the way I think about story before a camera ever turns on. The strongest lessons were practical: how scenes carry pressure, how performances change a cut, and how structure can make a small piece feel bigger than its budget.</p>\n<p>What stayed with me:</p>\n<ul>\n<li>A more disciplined way to break down scripts, scenes, and character motivation.</li>\n<li>Classroom critique from instructors with real production experience.</li>\n<li>A stronger foundation for the directing, editing, and documentary work I took on afterward.</li>\n</ul>\n"
  },
  {
    "title": "Co-Founder at Awaiten Films",
    "slug": "awaiten-films",
    "company": "Awaiten Films",
    "role": "Co-Founder",
    "location": "Bay Area, CA",
    "dateStart": "2018",
    "summary": "Co-founded a Bay Area production studio with Aalyan Aamir, making polished films, event pieces, and community media without losing the human part.",
    "tags": [
      "production",
      "directing",
      "editing",
      "cinematography"
    ],
    "href": "https://awaiten.com",
    "logo": "/media/polaroid-on-set.webp",
    "html": "<p>Awaiten is where I learned how to make the work hold up outside of my own head. That meant working with clients, shaping stories before a shoot, filming in imperfect rooms, editing under pressure, and still caring about the final frame.</p>\n<p>Highlights:</p>\n<ul>\n<li>Co-founded the studio with Aalyan Aamir.</li>\n<li>Worked across directing, cinematography, editing, motion graphics, and delivery.</li>\n<li>Helped produce community, brand, documentary, and event work that reached 1M+ views.</li>\n</ul>\n"
  },
  {
    "title": "Selected past collaborators",
    "slug": "early-projects",
    "company": "Wondertime · ALI · SABA · Loquat · others",
    "role": "Editor, VFX, Producer",
    "dateStart": "2017",
    "dateEnd": "2023",
    "summary": "Early work across community media, websites, short documentaries, nonprofit projects, and scrappy production teams.",
    "tags": [
      "editing",
      "vfx",
      "producing",
      "community"
    ],
    "logo": "/media/polaroid-mountains.webp",
    "html": "<p>Before the current chapter, I built range by saying yes to a lot of different creative problems. Some needed an editor. Some needed a producer. Some needed a website, a visual system, or someone willing to figure it out.</p>\n<p>Selected areas:</p>\n<ul>\n<li>Editing and visual effects for community and documentary projects.</li>\n<li>Web and creative systems work for organizations and early-stage ideas.</li>\n<li>Production support for Wondertime, ALI, SABA, Loquat, and other collaborators.</li>\n</ul>\n"
  },
  {
    "title": "Filmmaker & Editor (Freelance)",
    "slug": "independent-filmmaker",
    "company": "Freelance",
    "role": "Filmmaker, Editor, VFX",
    "location": "Worldwide",
    "dateStart": "2017",
    "summary": "Eight-plus years editing, shooting, fixing, and finishing videos for clients, communities, events, and personal projects.",
    "tags": [
      "editing",
      "vfx",
      "directing",
      "cinematography"
    ],
    "logo": "/media/polaroid-camera.webp",
    "html": "<p>Freelance work taught me the whole production loop. Find the story, plan what can actually be shot, capture enough to make the edit work, clean the details, and deliver something people want to watch.</p>\n<p>What this includes:</p>\n<ul>\n<li>Editing, color, sound cleanup, titles, and motion graphics.</li>\n<li>Camera operation and directing for documentary, event, brand, and community work.</li>\n<li>Practical fixes for small teams, tight budgets, bad rooms, and ambitious ideas.</li>\n</ul>\n"
  }
] satisfies Experience[]

export const archives = [
  {
    "slug": "instagram-1",
    "platform": "Instagram",
    "title": "Instagram: @mhadifilms",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "image": "/media/polaroid-on-set.webp",
    "summary": "Behind-the-scenes filmmaking, production stills, travel frames, and visual experiments."
  },
  {
    "slug": "linkedin-1",
    "platform": "Linkedin",
    "title": "Muhammad Hadi Yusufali on LinkedIn",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadimedia",
    "image": "/media/figma-mhadi-camera.png",
    "summary": "Public profile for work across sync. labs, Awaiten, Journey Tellers, filmmaking, editing, and creative technology."
  },
  {
    "slug": "linkedin-2",
    "platform": "Linkedin",
    "title": "DaVinci Resolve MCP post",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://www.linkedin.com/posts/mhadifilms_i-built-a-davinci-resolve-mcp-so-claude-can-activity-7455733839189946368-QHAG",
    "image": "/media/polaroid-camera.webp",
    "summary": "A public LinkedIn post on building a DaVinci Resolve MCP so Claude can work with editing timelines."
  },
  {
    "slug": "twitter-1",
    "platform": "Twitter",
    "title": "X: @mhadifilms",
    "date": "2026-06-07T00:00:00.000Z",
    "href": "https://x.com/mhadifilms",
    "image": "/media/polaroid-camera.webp",
    "summary": "Short-form notes on creative tools, AI video, filmmaking, and whatever is being built that week."
  },
  {
    "slug": "instagram-2",
    "platform": "Instagram",
    "title": "Production stills and frames",
    "date": "2026-06-06T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "image": "/media/polaroid-camera.webp",
    "summary": "A visual feed for frames from shoots, camera tests, edits, and everyday production work."
  },
  {
    "slug": "linkedin-3",
    "platform": "Linkedin",
    "title": "sync. labs work updates",
    "date": "2026-06-06T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadimedia",
    "image": "/media/figma-mhadi-camera.png",
    "summary": "Follow role updates from Chief of Staff and Head of Production work at sync. labs, a studio-grade lipsync and visual dubbing company."
  },
  {
    "slug": "twitter-2",
    "platform": "Twitter",
    "title": "Building-in-public updates",
    "date": "2026-06-06T00:00:00.000Z",
    "href": "https://x.com/mhadifilms",
    "image": "/media/figma-mhadi-camera.png",
    "summary": "Follow quick updates from experiments across software, post-production tooling, and creative workflows."
  },
  {
    "slug": "instagram-3",
    "platform": "Instagram",
    "title": "Short-form creative updates",
    "date": "2026-06-05T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "image": "/media/polaroid-beach.webp",
    "summary": "Follow lightweight updates that do not become full essays, videos, or portfolio projects."
  },
  {
    "slug": "linkedin-4",
    "platform": "Linkedin",
    "title": "Film, AI, and creator tooling notes",
    "date": "2026-06-05T00:00:00.000Z",
    "href": "https://www.linkedin.com/in/mhadimedia/recent-activity/all/",
    "image": "/media/polaroid-on-set.webp",
    "summary": "Recent LinkedIn activity around filmmaking, AI video workflows, creative tools, and startup operations."
  },
  {
    "slug": "twitter-3",
    "platform": "Twitter",
    "title": "Film and AI video notes",
    "date": "2026-06-05T00:00:00.000Z",
    "href": "https://x.com/mhadifilms",
    "image": "/media/polaroid-beach.webp",
    "summary": "Short thoughts on lipsync, visual dubbing, editing, models, and the UX of media creation."
  },
  {
    "slug": "instagram-4",
    "platform": "Instagram",
    "title": "Filmmaking snapshots",
    "date": "2026-06-04T00:00:00.000Z",
    "href": "https://www.instagram.com/mhadifilms",
    "image": "/media/polaroid-podcast.webp",
    "summary": "A profile-connected archive for visual work until Instagram API access is configured."
  },
  {
    "slug": "twitter-4",
    "platform": "Twitter",
    "title": "Live creative scratchpad",
    "date": "2026-06-04T00:00:00.000Z",
    "href": "https://x.com/mhadifilms",
    "image": "/media/polaroid-mountains.webp",
    "summary": "A profile-connected stream for small observations that do not need a full post or video."
  },
  {
    "slug": "substack-post-1",
    "platform": "Substack",
    "title": "من الرباط إلى الضريح: القصة التي لا تُروى",
    "date": "2026-05-01",
    "href": "https://mhadi.substack.com/p/295",
    "image": "https://substackcdn.com/image/fetch/$s_!WTVJ!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1af4c0cc-5f65-4234-a3f3-554a73eca46e_1376x768.png",
    "summary": "كيف روّضت السلطة روح الصوفية تمهيد: ماذا نعني بـ”الترويض”؟ قبل أن تقرأ سطرًا واحدًا، لا بدّ من تحديد المقصود بكلمة “روّضت” في هذه القصة، حتى لا يُساء فهمها...."
  },
  {
    "slug": "youtube-we-spent-a-week-exploring-tanzania-1",
    "platform": "YouTube",
    "title": "We Spent a Week Exploring Tanzania",
    "date": "2025-09-27",
    "href": "https://www.youtube.com/watch?v=Vy6LJhDH3Bk",
    "image": "https://i.ytimg.com/vi/Vy6LJhDH3Bk/hq720.jpg",
    "summary": "A few months ago, I had the chance to travel to Tanzania with friends for a week. Join us we chill with lions, swim with dolphins, visit one of the biggest..."
  },
  {
    "slug": "youtube-two-weeks-in-the-middle-east-with-my-school-part-3-2",
    "platform": "YouTube",
    "title": "Two Weeks in the Middle East with My School (Part 3)",
    "date": "2024-12-21",
    "href": "https://www.youtube.com/watch?v=6EblOyuUj34",
    "image": "https://i.ytimg.com/vi/6EblOyuUj34/hq720.jpg",
    "summary": "Watch part two first: https://youtu.be/TCrVwEoOvMk During the winter break of 2023, I went on a life-changing trip to the Middle East along with my high school..."
  },
  {
    "slug": "youtube-two-weeks-in-the-middle-east-with-my-school-part-2-3",
    "platform": "YouTube",
    "title": "Two Weeks in the Middle East with My School (Part 2)",
    "date": "2024-11-28",
    "href": "https://www.youtube.com/watch?v=TCrVwEoOvMk",
    "image": "https://i.ytimg.com/vi/TCrVwEoOvMk/hq720.jpg",
    "summary": "Watch the part one: https://youtu.be/iPT8JzCvBTE During the winter break of 2023, I went on a life-changing trip to the Middle East along with my high school..."
  },
  {
    "slug": "youtube-we-turned-a-youth-camp-into-a-documentary-4",
    "platform": "YouTube",
    "title": "We Turned a Youth Camp into a Documentary",
    "date": "2024-10-31",
    "href": "https://www.youtube.com/watch?v=04p3ls98W7Y",
    "image": "https://i.ytimg.com/vi/04p3ls98W7Y/hq720.jpg",
    "summary": "Watch the full documentary on @JourneyTellers: https://www.youtube.com/watch?v=zkvAHvcw8DE In May 2024, the Journey Tellers team partnered with Camp Noor to..."
  }
] satisfies ArchiveItem[]
