import fs from "node:fs/promises"
import path from "node:path"
import matter from "gray-matter"
import { marked } from "marked"

const root = process.cwd()
const contentDir = path.join(root, "content")
const outputFile = path.join(root, "src", "content", "generated.ts")

marked.use({
  gfm: true,
  breaks: false,
})

const byDateDesc = (a, b) => new Date(b.date ?? 0) - new Date(a.date ?? 0)

async function readJson(relativePath) {
  const file = path.join(contentDir, relativePath)
  return JSON.parse(await fs.readFile(file, "utf8"))
}

async function readCollection(name) {
  const dir = path.join(contentDir, name)
  const entries = await fs.readdir(dir, { withFileTypes: true }).catch(() => [])
  const markdownFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)

  const items = await Promise.all(
    markdownFiles.map(async (filename) => {
      const source = await fs.readFile(path.join(dir, filename), "utf8")
      const { data, content } = matter(source)
      const html = marked.parse(content, { async: false })

      return {
        ...data,
        slug: data.slug ?? filename.replace(/\.md$/, ""),
        html,
      }
    }),
  )

  return items
}

function assertRequiredFields(items, collection, fields) {
  for (const item of items) {
    for (const field of fields) {
      if (item[field] === undefined || item[field] === "") {
        throw new Error(`${collection}/${item.slug ?? "unknown"} is missing "${field}"`)
      }
    }
  }
}

const site = await readJson("site.json")
const pages = await readCollection("pages")
const projects = await readCollection("projects")
const posts = (await readCollection("posts"))
  .filter((post) => post.published !== false)
  .sort(byDateDesc)

assertRequiredFields(pages, "pages", ["title", "slug", "summary"])
assertRequiredFields(projects, "projects", ["title", "slug", "summary", "year"])
assertRequiredFields(posts, "posts", ["title", "slug", "summary", "date"])

const output = `// This file is generated by scripts/build-content.mjs. Do not edit by hand.
import type { Page, Post, Project, SiteConfig } from "./types"

export const site = ${JSON.stringify(site, null, 2)} satisfies SiteConfig

export const pages = ${JSON.stringify(pages, null, 2)} satisfies Page[]

export const projects = ${JSON.stringify(projects, null, 2)} satisfies Project[]

export const posts = ${JSON.stringify(posts, null, 2)} satisfies Post[]
`

await fs.mkdir(path.dirname(outputFile), { recursive: true })
await fs.writeFile(outputFile, output)
