import fs from "node:fs/promises"
import path from "node:path"
import matter from "gray-matter"
import { marked } from "marked"

const root = process.cwd()
const contentDir = path.join(root, "content")
const outputFile = path.join(root, "src", "content", "generated.ts")

marked.use({
  gfm: true,
  breaks: false,
})

const byExperienceOrder = (a, b) => {
  const orderDelta = Number(a.order ?? Number.MAX_SAFE_INTEGER) - Number(b.order ?? Number.MAX_SAFE_INTEGER)
  if (orderDelta !== 0) return orderDelta
  return new Date(b.dateStart ?? 0) - new Date(a.dateStart ?? 0)
}
const byDateDesc = (a, b) => new Date(b.date ?? 0) - new Date(a.date ?? 0)

async function readJson(relativePath) {
  const file = path.join(contentDir, relativePath)
  try {
    return JSON.parse(await fs.readFile(file, "utf8"))
  } catch (error) {
    if (error.code === "ENOENT") return null
    throw error
  }
}

async function readCollection(name, { renderBody = true } = {}) {
  const dir = path.join(contentDir, name)
  const entries = await fs.readdir(dir, { withFileTypes: true }).catch(() => [])
  const markdownFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)

  const items = await Promise.all(
    markdownFiles.map(async (filename) => {
      const source = await fs.readFile(path.join(dir, filename), "utf8")
      const { data, content } = matter(source)
      const item = {
        ...data,
        slug: data.slug ?? filename.replace(/\.md$/, ""),
      }
      if (renderBody) {
        item.html = marked.parse(content, { async: false })
      }
      return item
    }),
  )

  return items
}

function assertRequiredFields(items, collection, fields) {
  for (const item of items) {
    for (const field of fields) {
      if (item[field] === undefined || item[field] === "") {
        throw new Error(`${collection}/${item.slug ?? "unknown"} is missing "${field}"`)
      }
    }
  }
}

function assertProjectRefs(archives, projects) {
  const projectSlugs = new Set(projects.map((project) => project.slug))
  for (const archive of archives) {
    if (archive.project && !projectSlugs.has(archive.project)) {
      throw new Error(`archives/${archive.slug} references missing project "${archive.project}"`)
    }
  }
}

const site = (await readJson("site.json")) ?? {}

const experiences = (await readCollection("experiences")).sort(byExperienceOrder)
const projects = (await readCollection("projects")).sort((a, b) => String(a.title).localeCompare(String(b.title)))
const archives = (await readCollection("archives", { renderBody: false })).sort(byDateDesc)

assertRequiredFields(experiences, "experiences", ["title", "slug", "order", "company", "role", "dateStart", "summary"])
assertRequiredFields(projects, "projects", ["slug", "title", "type", "summary"])
assertRequiredFields(archives, "archives", ["slug", "platform", "projectType", "title", "href", "date"])
assertProjectRefs(archives, projects)

const output = `// This file is generated by scripts/build-content.mjs. Do not edit by hand.
import type { ArchiveItem, Experience, Project, SiteConfig } from "./types"

export const site = ${JSON.stringify(site, null, 2)} satisfies SiteConfig

export const experiences = ${JSON.stringify(experiences, null, 2)} satisfies Experience[]

export const projects = ${JSON.stringify(projects, null, 2)} satisfies Project[]

export const archives = ${JSON.stringify(archives, null, 2)} satisfies ArchiveItem[]
`

await fs.mkdir(path.dirname(outputFile), { recursive: true })
await fs.writeFile(outputFile, output)
